---
abstract: 'Paste to http://hpaste.org, the Haskell paste site'
author:
  - 'Dr Bean <drbean at (@, the at mark) cpan dot (. a dot) org'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200013, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Nopaste-Service-Hpaste
requires:
  App::Nopaste::Service: 0
resources:
  homepage: http://search.cpan.org/dist/App-Nopaste-Service-Hpaste/
  repository: http://svn.openfoundry.org/nopaste-hpaste
version: 0.02
